POST http://localhost:4000/admin/client/create
Content-Type: application/json

{
    "MOBILE_NO":"555",
    "F_NAME":"ff",
    "L_NAME":"ss"
}

###
POST http://localhost:4000/admin/client/address/add
Content-Type: application/json

{
    "ID":"6",
    "ADDRESS_ONE":"666",
    "ADDRESS_TWO":"666",
    "LATITUDE":"22.666",
    "LONGITUDE":"666.564"
}
###
POST http://localhost:4000/admin/client/tank/add
Content-Type: application/json

{
    "ID":"6",
    "TANK_VOLUME":"2",
    "TANK_PRICE":"100"
}
###
GET http://localhost:4000/admin/client/delete/9
###
GET http://localhost:4000/admin/clients/list
###
GET http://localhost:4000/admin/clients/address/list/6
###
GET http://localhost:4000/admin/clients/address/list/6
###
GET http://localhost:4000/admin/clients/tank/list/6
###
POST http://localhost:4000/admin/user/create
Content-Type: application/json

{
    "MOBILE_NO":"gg",
    "F_NAME":"ffgdgf",
    "L_NAME":"sfgfs",
    "PASSWORD":"hari"
}
